env:
  RESOURCE_GROUP: managedEnv20250417161852ResourceGroup
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnvValueSpace
  CONTAINER_REGISTRY_NAME: registryvaluespace
  CONTAINER_REGISTRY_LOGIN_SERVER: registryvaluespace.azurecr.io
  CONTAINER_APP_NAME: valuespace-chat-widget

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.MANAGEDENVVALUESPACE_SPN }}

      - name: Build and push Docker image
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
          acrUsername: ${{ secrets.REGISTRYVALUESPACE_USERNAME_B47C }}
          acrPassword: ${{ secrets.REGISTRYVALUESPACE_PASSWORD_B47C }}
          imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
